version: '3.9'
services:
  database:
    image: postgres
    env_file:
      - ./.env
    ports:
      - "5432:5432"
    volumes:
      - ./postgres/scripts:/docker-entrypoint-initdb.d
  web:
    build: .
    command: sh -c "sleep 2 && python manage.py makemigrations && python manage.py migrate && && gunicorn trans.wsgi:application --bind 0.0.0.0:8000"
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - database
  
  nginx:
    image: nginx:latest
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./static:/code/static
      - ./media:/code/media
    ports:
      "80:80"
    depends_on:
      - web